window.tpsng_data = [ { title: 'Healing justice practice space',
    url: 'http://etherpad.alliedmedia.org:8080/p/2017_TPSNG_healing_justice_practice_space',
    type: 'Practice Space' },
  { title: 'Mothering and Parenting the Revolution: Black and Afro-Latina Women Mothering explore mothering work/practice at the intersections of schools, academy and community through a critical media lens',
    url: 'http://etherpad.alliedmedia.org:8080/p/2017_TPSNG_mothering_and_parenting_the_revolution_',
    type: 'Track' },
  { title: 'Cultural Stewardship & Civic Engagement',
    url: 'http://etherpad.alliedmedia.org:8080/p/2017_TPSNG_cultural_stewardship_civic_engagement',
    type: 'Track' },
  { title: 'Community Technology',
    url: 'http://etherpad.alliedmedia.org:8080/p/2017_TPSNG_community_technology',
    type: 'Practice Space' },
  { title: 'Painting and All That Jazz',
    url: 'http://etherpad.alliedmedia.org:8080/p/2017_TPSNG_painting_and_all_that_jazz',
    type: 'Practice Space' },
  { title: 'Data Visualization for Community Organizers',
    url: 'http://etherpad.alliedmedia.org:8080/p/2017_TPSNG_data_visualization_for_community_organi',
    type: 'Practice Space' },
  { title: 'Build a Pirate Box!',
    url: 'http://etherpad.alliedmedia.org:8080/p/2017_TPSNG_build_a_pirate_box_',
    type: 'Practice Space' },
  { title: 'Architectures of Community',
    url: 'http://etherpad.alliedmedia.org:8080/p/2017_TPSNG_architectures_of_community',
    type: 'Track' },
  { title: '#BlackGirlMagic...For Real',
    url: 'http://etherpad.alliedmedia.org:8080/p/2017_TPSNG__blackgirlmagic_for_real',
    type: 'Track' },
  { title: 'Mindfulness and Creative Practice',
    url: 'http://etherpad.alliedmedia.org:8080/p/2017_TPSNG_mindfulness_and_creative_practice',
    type: 'Track' },
  { title: 'Diggin\' Deep: Remixing Research 2.0',
    url: 'http://etherpad.alliedmedia.org:8080/p/2017_TPSNG_diggin_deep_remixing_research_2_0',
    type: 'Track' },
  { title: 'Screaming From the Margins!: QTPOC & Young Women of Color Mastering the Art of Digital Organizing',
    url: 'http://etherpad.alliedmedia.org:8080/p/2017_TPSNG_screaming_from_the_margins_qtpoc_young_',
    type: 'Track' },
  { title: 'The Design Cypher: Merging Hip Hop Culture and Communty Development',
    url: 'http://etherpad.alliedmedia.org:8080/p/2017_TPSNG_the_design_cypher_merging_hip_hop_cultu',
    type: 'Track' },
  { title: 'Building A Youth-Led Movement with Human and Healing Justice as Foundations',
    url: 'http://etherpad.alliedmedia.org:8080/p/2017_TPSNG_building_a_youth_led_movement_with_huma',
    type: 'Track' },
  { title: '#WAGELOVE: ancestral technologies as ceremony, healing and resourcefulness',
    url: 'http://etherpad.alliedmedia.org:8080/p/2017_TPSNG__wagelove_ancestral_technologies_as_cer',
    type: 'Track' },
  { title: 'Social Justice in Faith Communities',
    url: 'http://etherpad.alliedmedia.org:8080/p/2017_TPSNG_social_justice_in_faith_communities',
    type: 'Track' },
  { title: 'Decolonizing Faith',
    url: 'http://etherpad.alliedmedia.org:8080/p/2017_TPSNG_decolonizing_faith',
    type: 'Track' },
  { title: 'Youth Track ',
    url: 'http://etherpad.alliedmedia.org:8080/p/2017_TPSNG_youth_track_',
    type: 'Track' },
  { title: 'TRUE Skool Milwaukee: Women leading a Social Movement',
    url: 'http://etherpad.alliedmedia.org:8080/p/2017_TPSNG_true_skool_milwaukee_women_leading_a_so',
    type: 'Track' },
  { title: 'TRUE KNOWLEDGELIBRARY',
    url: 'http://etherpad.alliedmedia.org:8080/p/2017_TPSNG_true_knowledgelibrary',
    type: 'Track' },
  { title: 'Spelling D',
    url: 'http://etherpad.alliedmedia.org:8080/p/2017_TPSNG_spelling_d',
    type: 'Network Gathering' },
  { title: 'Finding Truth & Reality in Urban Education',
    url: 'http://etherpad.alliedmedia.org:8080/p/2017_TPSNG_finding_truth_reality_in_urban_educatio',
    type: 'Practice Space' },
  { title: 'White Folks Dismantling',
    url: 'http://etherpad.alliedmedia.org:8080/p/2017_TPSNG_white_folks_dismantling',
    type: 'Track' },
  { title: 'Stories of Solidarity Economies',
    url: 'http://etherpad.alliedmedia.org:8080/p/2017_TPSNG_stories_of_solidarity_economies',
    type: 'Track' },
  { title: 'Coloured Television ',
    url: 'http://etherpad.alliedmedia.org:8080/p/2017_TPSNG_coloured_television_',
    type: 'Track' },
  { title: 'Survival Pending Renaissance...A Black Liberation Praxis',
    url: 'http://etherpad.alliedmedia.org:8080/p/2017_TPSNG_survival_pending_renaissance_a_black_li',
    type: 'Track' },
  { title: 'The Media Action Grassroots Network: Membership Assembly',
    url: 'http://etherpad.alliedmedia.org:8080/p/2017_TPSNG_the_media_action_grassroots_network_mem',
    type: 'Network Gathering' },
  { title: 'Families United 4 Justice:  Bridge-building with Families Affected by Police Violence',
    url: 'http://etherpad.alliedmedia.org:8080/p/2017_TPSNG_families_united_4_justice_bridge_buildi',
    type: 'Network Gathering' },
  { title: 'No Perfect Victims: At the Intersections of Gender Violence and Criminalization',
    url: 'http://etherpad.alliedmedia.org:8080/p/2017_TPSNG_no_perfect_victims_at_the_intersections',
    type: 'Network Gathering' },
  { title: 'Detroit & Puerto Rico Solidarity Exchange',
    url: 'http://etherpad.alliedmedia.org:8080/p/2017_TPSNG_detroit_puerto_rico_solidarity_exchange',
    type: 'Network Gathering' },
  { title: 'TransVisible ',
    url: 'http://etherpad.alliedmedia.org:8080/p/2017_TPSNG_transvisible_',
    type: 'Network Gathering' },
  { title: 'Activist as Entrepreneur: How Small Food Businesses Can Be Advocates for Change',
    url: 'http://etherpad.alliedmedia.org:8080/p/2017_TPSNG_activist_as_entrepreneur_how_small_food',
    type: 'Network Gathering' },
  { title: 'Re-imagining Movement Resource Strategies',
    url: 'http://etherpad.alliedmedia.org:8080/p/2017_TPSNG_re_imagining_movement_resource_strategi',
    type: 'Network Gathering' },
  { title: 'SUSTAINABILITY FOR RADICAL COMMUNITY SPACES ',
    url: 'http://etherpad.alliedmedia.org:8080/p/2017_TPSNG_sustainability_for_radical_community_sp',
    type: 'Network Gathering' },
  { title: 'FemTechNet Collaboration Space',
    url: 'http://etherpad.alliedmedia.org:8080/p/2017_TPSNG_femtechnet_collaboration_space',
    type: 'Network Gathering' },
  { title: 'Asian American and Pacific Islander Solidarity Economies Network Gathering',
    url: 'http://etherpad.alliedmedia.org:8080/p/2017_TPSNG_asian_american_and_pacific_islander_sol',
    type: 'Network Gathering' },
  { title: 'Seraphine Collective Presents: Collective Knowledge: A Network Gathering for Feminist, Womanist, and other Anti-Oppressive art and music collectives',
    url: 'http://etherpad.alliedmedia.org:8080/p/2017_TPSNG_seraphine_collective_presents_collectiv',
    type: 'Network Gathering' },
  { title: 'AMALGAMATION: Mixed Race, Mixed Identities, Mixed Media, Mixed Meaning',
    url: 'http://etherpad.alliedmedia.org:8080/p/2017_TPSNG_amalgamation_mixed_race_mixed_identitie',
    type: 'Network Gathering' },
  { title: 'Groundswell: Oral History for Social Change ',
    url: 'http://etherpad.alliedmedia.org:8080/p/2017_TPSNG_groundswell_oral_history_for_social_cha',
    type: 'Network Gathering' },
  { title: 'Rad Care; Beyond Social Justice',
    url: 'http://etherpad.alliedmedia.org:8080/p/2017_TPSNG_rad_care_beyond_social_justice',
    type: 'Network Gathering' },
  { title: 'AMP Sponsored Projects Network Gathering',
    url: 'http://etherpad.alliedmedia.org:8080/p/2017_TPSNG_amp_sponsored_projects_network_gatherin',
    type: 'Network Gathering' },
  { title: 'InterGalactic Conspiracy of Childcare Collectives Network Gathering',
    url: 'http://etherpad.alliedmedia.org:8080/p/2017_TPSNG_intergalactic_conspiracy_of_childcare_c',
    type: 'Network Gathering' },
  { title: 'Really Rad Radio & Video! (3RV)',
    url: 'http://etherpad.alliedmedia.org:8080/p/2017_TPSNG_really_rad_radio_video_3rv_',
    type: 'Practice Space' },
  { title: 'Creating Community in Our Home Kitchens Practice Space',
    url: 'http://etherpad.alliedmedia.org:8080/p/2017_TPSNG_creating_community_in_our_home_kitchens',
    type: 'Practice Space' },
  { title: 'Kids, Caregivers, & Community Transform the World Practice Space',
    url: 'http://etherpad.alliedmedia.org:8080/p/2017_TPSNG_kids_caregivers_community_transform_the',
    type: 'Practice Space' },
  { title: 'BOOM Concepts Salon: A Field Building Community Space to Create Artist Pipelines for Cultural Resistance and Radical Innovation',
    url: 'http://etherpad.alliedmedia.org:8080/p/2017_TPSNG_boom_concepts_salon_a_field_building_co',
    type: 'Practice Space' },
  { title: 'Radical Librarians and Archivists',
    url: 'http://etherpad.alliedmedia.org:8080/p/2017_TPSNG_radical_librarians_and_archivists',
    type: 'Track' },
  { title: 'Resourcing and Sustaining Our Movements',
    url: 'http://etherpad.alliedmedia.org:8080/p/2017_TPSNG_resourcing_and_sustaining_our_movements',
    type: 'Track' },
  { title: 'Design Justice',
    url: 'http://etherpad.alliedmedia.org:8080/p/2017_TPSNG_design_justice',
    type: 'Track' },
  { title: 'Dreaming Our Electric Future: Organizing the Next Waves of Community Technology',
    url: 'http://etherpad.alliedmedia.org:8080/p/2017_TPSNG_dreaming_our_electric_future_organizing',
    type: 'Track' },
  { title: 'Poetry & Publishing: Activating Publics',
    url: 'http://etherpad.alliedmedia.org:8080/p/2017_TPSNG_poetry_publishing_activating_publics',
    type: 'Track' },
  { title: 'Disrupting Mainstream History: Memory Keeping, Storytelling, and Archives',
    url: 'http://etherpad.alliedmedia.org:8080/p/2017_TPSNG_disrupting_mainstream_history_memory_ke',
    type: 'Track' },
  { title: 'Securing our spaces, security culture in our online and offline communities',
    url: 'http://etherpad.alliedmedia.org:8080/p/2017_TPSNG_securing_our_spaces_security_culture_in',
    type: 'Track' },
  { title: 'Sound & revolution: music and social justice',
    url: 'http://etherpad.alliedmedia.org:8080/p/2017_TPSNG_sound_revolution_music_and_social_justi',
    type: 'Track' },
  { title: 'Food Matters',
    url: 'http://etherpad.alliedmedia.org:8080/p/2017_TPSNG_food_matters',
    type: 'Track' },
  { title: 'Eating Our Feelings in Diaspora',
    url: 'http://etherpad.alliedmedia.org:8080/p/2017_TPSNG_eating_our_feelings_in_diaspora',
    type: 'Network Gathering' },
  { title: 'The Healing Justice Track',
    url: 'http://etherpad.alliedmedia.org:8080/p/2017_TPSNG_the_healing_justice_track',
    type: 'Practice Space' },
  { title: 'Abundant Bodies: Fat Lovin\' Media Futures',
    url: 'http://etherpad.alliedmedia.org:8080/p/2017_TPSNG_abundant_bodies_fat_lovin_media_futures',
    type: 'Network Gathering' },
  { title: 'Building an inclusive and radical housing justice movement',
    url: 'http://etherpad.alliedmedia.org:8080/p/2017_TPSNG_building_an_inclusive_and_radical_housi',
    type: 'Network Gathering' },
  { title: 'Art as social Resistace',
    url: 'http://etherpad.alliedmedia.org:8080/p/2017_TPSNG_art_as_social_resistace',
    type: 'Practice Space' } ];
